name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew build

  dump-sources:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/setup-gradle@v5
      - name: Remove outdated sources and dump new sources
        run: |
          rm -rf *-alpha* # Remove the last alpha version sources.
          rm -rf *-beta* # Remove the last beta version sources.
          rm -rf *-rc* # Remove the last rc version sources.
          ./gradlew dumpSources
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@v8
        id: create-pull-request
        with:
          commit-message: |
            Update AGP sources to the latest

            _Auto-generated by `dump-sources` workflow._
          title: Update AGP sources to the latest
          body: _Auto-generated by `dump-sources` workflow._
          branch: actions/dump-sources
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com> # Same as `committer`.'
          token: ${{ steps.app-token.outputs.token }}
          delete-branch: true
          base: defer-dump-steps
      - name: Merge Pull Request
        if: steps.create-pull-request.outputs.pull-request-number != ''
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr merge ${{ steps.create-pull-request.outputs.pull-request-number }} --auto --rebase
